# Generated by Django 2.1.11 on 2020-09-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0002_helper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helper',
            options={'verbose_name': '帮助信息', 'verbose_name_plural': '帮助信息'},
        ),
    ]
